### ISSUE TITLE
Failed reading line 014810000312

### ISSUE THREAD

**Issue by jschmied** [egore/libldt3#3]
https://www.docnet.de/download/LDT.1001.02-13.11.08.pdf

8100     Summe  aller Feldlängen des Satzes in Bytes

Exception in thread "main" java.lang.IllegalArgumentException: Failed reading line 014810000312 (2), current stack: [libldt3.model.saetze.LaborDatenpaketHeader@2678b5e8]
	at libldt3.LdtReader.handleInput(LdtReader.java:329)
	at libldt3.LdtReader.lambda$0(LdtReader.java:121)
	at libldt3.LdtReader$$Lambda$7/0x00000000dc3da4e0.accept(Unknown Source)

----
01380008220
014810000312
0199212LDT1014.01
01002010
0580203xxxxxxxxxxxxxxxxxxxxx
0180212000000000
0380211xxxxxxxxxxxxxxxxxxxxx
0230205xxxxxxxxx
0140215xxxxxx
0150216Berlin
----

**Comment by egore** [comment]
Die Bibliothek unterstützt nur LDT 3, keine Vorgängerversionen
